### ISSUE TITLE
Gzip memory error

### ISSUE THREAD

**Issue by ShawnKwak** [Neo23x0/yarGen#13]
I get a memory error during the update command.
'python yarGen.py -update'

There are my memory state.
Total Memory : 15.8GB
Used Memory : 8.0GB

There are error message.
[+] Loading ./dbs/good-strings-part5.db ...
Traceback (most recent call last):
  File "yarGen.py", line 1895, in <module>
    good_pickle = load(get_abs_path(filePath))
  File "yarGen.py", line 1598, in load
    data = file.read()
  File "C:\Python27\lib\gzip.py", line 261, in read
    self._read(readsize)
  File "C:\Python27\lib\gzip.py", line 320, in _read
    self._add_read_data( uncompress )
  File "C:\Python27\lib\gzip.py", line 338, in _add_read_data
    self.extrabuf = self.extrabuf[offset:] + data
MemoryError

**Comment by Neo23x0** [comment]
The update from the online databases uses "--update". (double minus sign)

If you want to update a specific local database, you would use "-u", but I haven't tested this function after the last refactoring, because "-u" for updating database sets is not recommended anymore. If you want to increase the set of strings and opcodes, create new databases with ```-c -i identifier -g /path/to/goodware```.

**Comment by Neo23x0** [comment]
Make sure to use the current 'master' branch version or the bugfix release 0.17.1 that I've just published.
